### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by CRD716** [nlscc/samloader#54]
## Description
While attempting to download GT-i9100 firmware this error occurs. (Btw if you can give me any help with it that would be awesome, this model seems to have vanished)

## Reproduction Steps
samloader -m GT-I9100 -r XSA checkupdate
I9100XWLSH/I9100XSALSA/I9100XXLS9/I9100XWLSH
samloader -m GT-I9100 -r XSA download -v I9100XWLSH/I9100XSALSA/I9100XXLS9/I9100XWLSH -o GT1900

## Output
`size = int(root.find("./FUSBody/Put/BINARY_BYTE_SIZE/Data").text)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'`

## Environment
Python 3.10, Windows 10

**Comment by ysfchn** [comment]
Samsung's servers somehow returns inconsistent data which varies to devices. `BINARY_BYTE_SIZE` key tells the firmware file size, so Samloader can track the download progress. However, because of this "inconsistency", some values returns blank and that causes errors in Samloader and other Samsung firmware downloaders.

Also, yeah, looks like model may have vanished because I can't see any filename returned from Samsung's servers (which is required to download the firmware) for this model.

**Comment by nlscc** [comment]
unfortunately this firmware appears to have been deleted from Samsung's servers - the filename is empty. i've added a check for this and a better error message but the file is gone
